version: "2.2"
services:
  fluent-bit:
    image: "fluent/fluent-bit:latest"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "5710:5710"
  service-a:
    build: "./serviceA"
    depends_on:
      - fluent-bit
  service-b:
    build: "./serviceB"
    depends_on:
      - fluent-bit
  service-c:
    build: "./serviceC"
    ports:
      - "80:80"
    depends_on:
      - fluent-bit